<a href="https://colab.research.google.com/github/anumit-web/python-interview-2024/blob/main/machine%20learning/Unsupervised_Learning_clustering_type_iris_flower_clustering_Gaussian_mixture_model_(GMM).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Intelligence

# Machine Learning

# Deep Learning

# PyTorch

---
---
---


# Python Code

# Python code

In [1]:
import torch

In [2]:
torch.cuda.is_available()

False

In [3]:
import torch

# Create a scalar tensor
scalar_tensor = torch.tensor(5.0)
print(scalar_tensor)

scaler_tensor2 = torch.tensor(8)
scaler_tensor2

tensor(5.)


tensor(8)

In [4]:

vector_tensor1 = torch.tensor([1,2,3])
print(vector_tensor1)

list1 = [89,37,89,23]
vector_tensor2 = torch.tensor(list1)
print(vector_tensor2)

tensor([1, 2, 3])
tensor([89, 37, 89, 23])


In [5]:

import torch

# Create a matrix tensor
matrix_tensor = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])
print(matrix_tensor)



tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [6]:

# Create a 3d tensor
tensor_3d = torch.tensor([[[1, 2], [3,4]], [[5, 6], [7, 8]]])
print(tensor_3d)


tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


---
---
---


---
---
---


---
---
---

---
---
---
