<a href="https://colab.research.google.com/github/anumit-web/ML-Masterlist-2024/blob/main/Numpy/Numpy_Masterlist_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
# Masterlist

In [19]:
import numpy as np

In [20]:
print (np.__version__)

1.26.4


In [21]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [23]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Creating Arrays from Python Lists

In [24]:
import numpy as np

In [25]:
# Integer array
a1 = np.array([1, 4, 2, 5, 3])
a1

array([1, 4, 2, 5, 3])

In [26]:
a2 = np.array([3.14, 4, 2, 3])

In [27]:
a3 = np.array([1, 2, 3, 4], dtype=np.float32)
a3

array([1., 2., 3., 4.], dtype=float32)

In [29]:
a4 = np.array([range(i, i + 3) for i in [2, 4, 6]])
a4

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Creating Arrays from Scratch

In [30]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
np.zeros(10, dtype= np.float32)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)